backend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.http import HttpResponseRedirect
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token

from core.views import core_view

urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path("", include('core.urls', namespace='core')),
    path("", view=core_view, name="main-app"),
    path("users/", include('users.urls', namespace='users')),
    path("accounts/", include("allauth.urls")),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    path("contact/", TemplateView.as_view(template_name="pages/contact.html"), name="contact"),
    path("posts/", include("posts.urls", namespace='posts')),

    #favicons
    path('favicon.ico', lambda x: HttpResponseRedirect(settings.STATIC_URL + 'images/favicons/48/favicon.ico')),
    path('favicon.ico', lambda x: HttpResponseRedirect(settings.STATIC_URL + 'images/favicons/96/favicon.ico')),
    path('favicon.ico', lambda x: HttpResponseRedirect(settings.STATIC_URL + 'images/favicons/128/favicon.ico')),
    path('robots.txt', TemplateView.as_view(template_name="robots.txt", content_type='text/plain')),
    #path('sitemap.xml', TemplateView.as_view(template_name="sitemap.xml", content_type='text/xml')),
    path('humans.txt', TemplateView.as_view(template_name="humans.txt", content_type='text/plain')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("backend.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    # Login via browsable api
    path("api-auth/", include("rest_framework.urls")),
    # Login via REST
    path("api/rest-auth/", include("rest_auth.urls")),
    # Registration via REST
    path("api/rest-auth/registration/", include("rest_auth.registration.urls")),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    

core/urls.py
from django.urls import path, re_path
from django.contrib.auth.decorators import login_required
from core.views import core_view, about_view


app_name = "core"
urlpatterns = [
    # re_path(r"^.*$", view=main_core_view, name="core-main"),
    #path("", view=core_view, name="main-app"),
    path("about", view=about_view, name="about-app"),
    path("projects", view=about_view, name="projects-app"),

]

posts/urls.py
from posts.views import (
    post_list_view,
    post_detail_view,
    post_create_view,
    post_update_view,
    post_delete_view
)
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'posts'
urlpatterns = [
    path('', view=post_list_view, name='list'),
    path('<slug:slug>', view=post_detail_view, name='detail'),
    path('create/', view=post_create_view, name='create'),
    path('<slug:slug>/update/', view=post_update_view, name='update'),
    path('<slug:slug>/delete/', view=post_delete_view, name='delete'),
]

posts/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils.text import slugify
from markdown_deux import markdown
User = getattr(settings, 'AUTH_USER_MODEL')


class Post(models.Model):
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        related_query_name='post'
    )
    headline = models.CharField(max_length=240)
    # subheadline = models.CharField(max_length=240, blank=True)
    slug = models.SlugField(max_length=255, unique=True, editable=False)
    description = models.CharField(max_length=240, blank=True)
    # prerequisite = models.TextField(blank=True)
    content = models.TextField()
    content1 = models.TextField(blank=True)
    conclusion = models.TextField(blank=True)
    created = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)

    class Meta:
        ordering = ['-updated']
        unique_together = ('headline', 'slug')

    def __str__(self):
        return self.headline

    
    def get_absolute_url(self):
        return reverse('posts:detail', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        value = self.headline
        self.slug = slugify(value, allow_unicode=True)
        super().save(*args, **kwargs)

    def get_markdown(self):
        content = self.content
        return markdown(content)
    

posts/api/views.py
from rest_framework import viewsets, generics, status
from rest_framework.generics import get_object_or_404
from rest_framework.exceptions import ValidationError
from rest_framework.views import APIView
from rest_framework.response import Response
from django.utils.translation import gettext_lazy as _
from rest_framework.permissions import IsAuthenticated
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin

from .serializers import PostSerializer
from posts.models import Post
from users.api.permissions import ReadOnly, IsAdminOrReadOnly, IsAuthorOrReadOnly


class PostViewSet(viewsets.ModelViewSet):
    serializer_class = PostSerializer
    permission_classes = [IsAdminOrReadOnly]
    queryset = Post.objects.all()
    lookup_field = 'slug'

    def perform_create(self, serializer):
        serializer.save(author=self.request.user)

posts/views.py
from django.shortcuts import render
from .models import Post
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404


class PostListView(ListView):
    model = Post
    template_name = 'posts/post_list.html'
    ordering = ['-updated']
    posts = Post.objects.all()
    context_object_name = 'posts'

    def get_context_data(self, *args, **kwargs):
        context = super(PostListView, self).get_context_data(*args, **kwargs)
        context['headline'] = 'New Post'
        context['description'] = 'Awesome new post'
        return context

post_list_view = PostListView.as_view()

class PostDetailView(DetailView):
    model = Post
    template_name = 'posts/post_detail.html'
    

post_detail_view = PostDetailView.as_view()

class PostCreateView(LoginRequiredMixin,CreateView):
    model = Post
    template_name = 'posts/post_form.html'
    fields = ['headline', 'description', 'content', 'content1', 'conclusion',]

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

post_create_view = PostCreateView.as_view()

class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    template_name = 'posts/post_form.html'
    fields = ['headline', 'description', 'content','content1', 'conclusion',]

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

post_update_view = PostUpdateView.as_view()


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    template_name = 'post/post_confirm_delete.html'
    success_url = reverse_lazy('draft_list')
    
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.user:
            return True
        return False
post_delete_view = PostDeleteView.as_view()

templates/posts/base.html
{% extends "base.html" %}
{% block title %}{% block head_title %}{% endblock head_title %}{% endblock title %}

{% block content %}
<div class="row">
  <div class="col">
    {% block inner %}{% endblock %}
  </div>
</div>
{% endblock %}

templates/posts/post_confirm_delete.html
{% extends "draft/base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block head_title %}Delete Post{% endblock %}
{% block description %}Delete post form{% endblock %}

{% block inner %}
<form action="." method="POST" enctype="multipart/form-data" autocomplete="off" novalidate>
{% csrf_token %}
<h4>Draft Delete {{ object.headline }}</h4>
    <button type="submit" class="btn btn-danger text-danger">DELETE POST</button>
    <a class="btn btn-warning text-warning" href="{% url 'posts:detail' posts.slug %}">Cancel</a>
                    
</form>
           

{% endblock %}

templates/posts/post_detail.html
{% extends "posts/base.html" %}
{% load static i18n %}


{% block head_title %}{{ object.headline }}{% endblock %}
{% block description %}{{ object.description }}{% endblock %}

{% block inner %}
<h3>{{ object.headline }}</h2>
<p>{{ object.get_markdown|safe }}</p>
{% endblock %}

templates/posts/post_form.html
{% extends "posts/base.html" %}
{% load static i18n %}
{% load crispy_forms_tags %}

{% with request.resolver_match.url_name as url_name %}
    {% block head_title %}{% if request.path == '/posts/create/' %}Create Post{% else %}Update Post{{ object.headline }}{% endif %}{% endblock %}
    {% block description %}{% if request.path == '/posts/create/' %}Create post form{% else %}Update {{ object.description }}{% endif %}{% endblock %}
{% endwith %}
{% block inner %}

{% url 'posts:create' as create %}
{% url 'posts:update' posts.slug as update %}

<form action="." method="POST" enctype="multipart/form-data" autocomplete="off" novalidate>
 {% csrf_token %}
 {% if request.path == create %}
    <h4>Create Post Form</h4>
 {% else %}
    <h2>Update Post Form</h2>
{% endif %}
{{ form|crispy }}
{% if request.path == create %}
    <button type="submit" class="btn btn-primary">CREATE POST</button>
{% else%}
    <button type="submit" class="btn btn-primary">UPDATE POST</button>
{% endif %}


</form>


{% endblock %}

templates/posts/post_list.html
{% extends "posts/base.html" %}
{% load static i18n %}

{% block head_title %}{% endblock %}
{% block description %}{% endblock %}

{% block inner %}
{% for post in posts %}
<h3><a style="color:#5c6670;text-decoration:none;padding-bottom:2px;border-bottom:2px solid #00bcd4;" href="{{ post.get_absolute_url }}">{{ post.headline }}</a></h3>
<small>{{ post.description }}</small>
{% endfor %}
{% endblock %}