backend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.http import HttpResponseRedirect
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token

from core.views import core_view

urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path("", include('core.urls', namespace='core')),
    path("", view=core_view, name="main-app"),
    path("users/", include('users.urls', namespace='users')),
    path("accounts/", include("allauth.urls")),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    path("contact/", TemplateView.as_view(template_name="pages/contact.html"), name="contact"),
    path("posts/", include("posts.urls", namespace='posts')),

    #favicons
    path('favicon.ico', lambda x: HttpResponseRedirect(settings.STATIC_URL + 'images/favicons/48/favicon.ico')),
    path('favicon.ico', lambda x: HttpResponseRedirect(settings.STATIC_URL + 'images/favicons/96/favicon.ico')),
    path('favicon.ico', lambda x: HttpResponseRedirect(settings.STATIC_URL + 'images/favicons/128/favicon.ico')),
    path('robots.txt', TemplateView.as_view(template_name="robots.txt", content_type='text/plain')),
    #path('sitemap.xml', TemplateView.as_view(template_name="sitemap.xml", content_type='text/xml')),
    path('humans.txt', TemplateView.as_view(template_name="humans.txt", content_type='text/plain')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("backend.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    # Login via browsable api
    path("api-auth/", include("rest_framework.urls")),
    # Login via REST
    path("api/rest-auth/", include("rest_auth.urls")),
    # Registration via REST
    path("api/rest-auth/registration/", include("rest_auth.registration.urls")),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    

core/urls.py
from django.urls import path, re_path
from django.contrib.auth.decorators import login_required
from core.views import core_view, about_view


app_name = "core"
urlpatterns = [
    # re_path(r"^.*$", view=main_core_view, name="core-main"),
    #path("", view=core_view, name="main-app"),
    path("about", view=about_view, name="about-app"),
    path("projects", view=about_view, name="projects-app"),

]

posts/urls.py
from posts.views import (
    post_list_view,
    post_detail_view,
    post_create_view,
    post_update_view,
    post_delete_view
)
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'posts'
urlpatterns = [
    path('', view=post_list_view, name='list'),
    path('<slug:slug>', view=post_detail_view, name='detail'),
    path('create/', view=post_create_view, name='create'),
    path('<slug:slug>/update/', view=post_update_view, name='update'),
    path('<slug:slug>/delete/', view=post_delete_view, name='delete'),
]

templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Arnel Imperial{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="320">
    <meta name="description" content="{% block description%}{% endblock description%}">
    <link type="text/plain" rel="author" href="https://wwww.arnelimperial.com/humans.txt"> 
    <link rel="canonical" href="https://arnelimperial.com" />
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://www.arnelimperial.com/">
    <meta property="og:title" content="Arnel Imperial">
    <meta property="og:description" content="Arnel Imperial's internet site.">
    <meta property="og:image" content="">
    <meta property="twitter:card" content="summary_large_image">
    <meta property="twitter:url" content="https://arnelimperial.com/">
    <meta property="twitter:title" content="Arnel Imperial">
    <meta property="twitter:description" content="Arnel Imperial's internet site.">
    <meta property="twitter:image" content="">
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="{% static 'css/journal-bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/project.css' %}">
    {% block css %}
    {% endblock %}

  </head>

  <body class="page-top">
    <div class="nav__div">
      <nav class="py-3 navbar navbar-expand-lg navbar-light bg-light fixed-top" id="mainNav">
        <div class="container">
          <a class="navbar-brand js-scroll-trigger font-weight-bold" href="{% url 'main-app' %}">Arnel Imperial</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            {% with request.resolver_match.url_name as url_name %}
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a class="nav-link font-weight-bold" href="{% url 'main-app' %}">{% trans 'Home' %}</a>
              </li>
              <li class="nav-item {% if url_name == 'core:about-app' %}active{% endif %}">
                <a class="nav-link font-weight-bold {% if url_name == 'core:about-app' %}nav__item{% endif %}" href="{% url 'core:about-app' %}">{% trans 'About' %}</a>
              </li> 
              <li class="nav-item {% if url_name == 'core:projects-app' %}active{% endif %}">
                <a class="nav-link font-weight-bold {% if url_name == 'core:projects-app' %}nav__item{% endif %}" href="{% url 'core:projects-app' %}">{% trans 'Projects' %}</a>
              </li> 
              <li class="nav-item {% if url_name == 'contact' %}active{% endif %}">
                <a class="nav-link font-weight-bold {% if url_name == 'contact' %}nav__item{% endif %}" href="{% url 'contact' %}">{% trans 'Contact' %}</a>
              </li>
              {% if request.user.is_authenticated %}
              <li class="nav-item {% if request.path == '/posts/' %}active{% endif %}">
                <a class="nav-link font-weight-bold {% if request.path == '/posts/' %}nav__item{% endif %}" href="{% url 'posts:list' %}">{% trans "Post List" %}</a>
              </li>
              <li class="nav-item {% if request.path == main_user %}active{% endif %}">
                <a class="nav-link font-weight-bold {% if request.path == main_user %}nav__item{% endif %}" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
              </li>

              <li class="nav-item {% if url_name == 'account_logout' %}active{% endif %}">
                <a class="nav-link font-weight-bold {% if url_name == 'account_logout' %}nav__item{% endif %}" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
              </li>
              {% else %}
              <li class="nav-item {% if url_name == 'account_login' %}active{% endif %}">
                <a class="nav-link font-weight-bold {% if url_name == 'account_login' %}nav__item{% endif %}" href="{% url 'account_login' %}">{% trans 'Portal' %}</a>
              </li>
              {% endif %}

            </ul>
            {% endwith %}
          </div>
        </div>
      </nav>

    </div>
    <div class="container">
      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
          {% endfor %}
      {% endif %}
    </div>
    <div class="container mt-5">
      {% block content %}
      {% endblock content %}
    </div> 

    {% block modal %}{% endblock modal %}
      <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
      <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/1.1.0/marked.min.js"></script>
      <script type="text/javascript">
      $(document).ready(function(){
        $("#content-markdown").each(function(){
          var mcontent = $(this).text()
          var markedContent = marked(mcontent) 
          $(this).html(markedContent)

        })
        
    })
    </script>
      
    {% block javascript %}

    {% endblock javascript %}
  </body>
</html>
 

templates/index-dev.html
{% extends "base.html" %}
{% load render_bundle from webpack_loader %}

{% block content %}
<noscript>
    <strong>We're sorry but frontend doesn't work properly without JavaScript enabled. Please enable it to continue.</strong>
</noscript>

<div id="app"></div>

<!-- built files will be auto injected -->
{% render_bundle 'app' %}
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load static i18n %}

{% block css %}
<link rel="stylesheet" href="{% static 'bundle.css' %}">

{% endblock %}

{% block content %}
<noscript>
    <strong>We're sorry but frontend doesn't work properly without JavaScript enabled. Please enable it to continue.</strong>
</noscript>
<div id="app"></div>
{% endblock %}

{% block javascript %}
<script src="{% static 'bundle.js' %}"></script>

{% endblock %}